### ISSUE TITLE
Getting error while running OCPI model

### ISSUE THREAD

**Issue by anukp12** [Llocer/llocer_ev_examples#1]
I am trying to run OCPI module through postman, but getting a Method Not Found error.

I have included @WebServlet(urlPatterns = "/ocpi") in OcpiTestLocationReceiver.java file and run the same in tomcat server.
Below is the request:
curl --location --request PUT 'http://127.0.0.1:8080/ocpi/221/locations/ES/MCS/location1/' \
--header 'Authorization: Token TMP' \
--header 'X-Request-ID: oamRequestId' \
--header 'X-Correlation-ID: oamCorrelationId' \
--header 'OCPI-to-country-code: ES' \
--header 'OCPI-to-party-id: MCS' \
--header 'Content-Type: application/json' \
--data-raw '{
	"country_code": "ES",
	"party_id": "MCS",
	"id": "location1",
	"publish": true,
	"address": "Sesame street",
	"country": "ESP",
	"coordinates": { "latitude": "my latitude", "longitude": "my longitude" },
	"timezone": "Europe/Madrid"
}'

Could you please help me to sort it out?

**Comment by Llocer** [comment]
Hi,

Thanks for your interest in these libraries.

Could you provide the complete error message? (in particular, name of the missing method)

Kind regards.

**Comment by anukp12** [comment]
Hi Llocer,

Thank you for your reply.

I am getting HTTP status 405- Method not allowed.
Seems to be issue with the URL in the request.

Thanks,
Anu

**Comment by Llocer** [comment]
Hi,

Could you see if tomcat log files are generated. In particular, some file with a line as:

`OcpiServlet.service: PUT  ...`

Moreover, I suppose you have not created a config file `/etc/ocpi.conf`, thus, default config is being used. As you have defined an  URL start of `/ocpi`, a file /etc/ocpi.conf should exists with content:

```
{
	"public_url": "http://127.0.0.1:8080/ocpi/",
	"private_uri_length":  1
}
```

I suggest that, before to test the PUT of locations, you test the endpoints and versions modules (mandatory in any OCPI node). That is:

-  execute GET http://127.0.0.1:8080/ocpi to retrieve the versions
-  execute GET http://127.0.0.1:8080/ocpi/221 to retrieve endpoints for version 221



Kind regards.

**Comment by anukp12** [comment]
Thanks for your explanation.

 I am getting HTTP Status 404 – Not Found while retrieving versions.

I have also tried to run your repo as such, by just making it to a dynamic web module. There also I am facing the same issue while retrieving versions.

**Comment by Llocer** [comment]
Anything at Tomcat logs?

**Comment by anukp12** [comment]
No

**Comment by Llocer** [comment]
If anything is received by the servlet
, some lines are written at tomcat logs.


404 not found could have a lot of reason, including tomcat not running, no
war loaded, ...

Could you share your test war file? On Saturday I can verify it.

**Comment by anukp12** [comment]
Giving war name after port number resolved the issue.

Now I am getting Unknown Authorization error message while retrieving
version.

Is there any default token for testing purpose?

**Comment by Llocer** [comment]
Yes, in Tomcat, war name is added to the URL, except if the war name is ROOT.war.

About the default token. In example file [OcpiTestLocationReceiver.java](https://github.com/Llocer/llocer_ev_examples/blob/master/src/main/java/com/llocer/ev/example/OcpiTestLocationReceiver.java) you will find an static method called `makeLink` . When executed, it inits a link with initial token `Token TMP` and presenting our OCPI node as an EMSP. In a Tomcat test environment, this method can be called at server start. See file [MainStartStop.java ](https://github.com/Llocer/llocer_ev_examples/blob/master/src/main/java/com/llocer/ev/example/MainStartStop.java) with an example about how to do that (warning: this file also inits a OCPP server, probably you must simplify it).

About generation of random tokens:

OCPI protocol states that initial token must be replaced by random one when the peer presents its credentials. This requirement is fulfilled by OCPI library. However, in a test environment this feature made more difficult implement simple test scripts, as the ones based on curl commands. For this reason, the librarian has a configurable flag `testing_no_change_credentials` (default false). If config file /etc/ocpi.conf contains a line as:

```
{
...
	"testing_no_change_credentials":  true
}
```

the token is not changed when a peer presents the credentials.

Finally, are tomcat logs already showing debug information about these elements?

**Comment by anukp12** [comment]
Thank you for giving explanation.

Now version and location module is working fine. But for credentials, I am getting Method Not Allowed.

curl --location --request POST 'http://localhost:8080/llocer_ocpi/ocpi/credentials' \
--header 'Authorization: Token TMP' \
--header 'X-Request-ID: oamRequestId' \
--header 'X-Correlation-ID: oamCorrelationId' \
--header 'OCPI-to-country-code: ES' \
--header 'OCPI-to-party-id: MCS' \
--header 'Content-Type: application/json' \
--data-raw '{
 "token": "TMP",
 "url": "http://127.0.0.1:8080/ocpi/",
 "roles": [{
 "role": "CPO",
 "party_id": "MCS",
 "country_code": "NL",
 "business_details": {
 "name": "Example Operator"
 }
 }, {
 "role": "EMSP",
 "party_id": "MCS",
 "country_code": "NL",
 "business_details": {
 "name": "Example Provider"
 }
 }]
}
'

Could you please help me to sort it out.

**Comment by Llocer** [comment]
Nice to known versions, endpoints and location are now ok.

According to the OCPI standard, credentials chapter:

> POST Method
> [...]
> This method MUST return a HTTP status code 405: method not allowed if the client has already been registered before
> 

and:

> PUT Method
> [...]
> This method MUST return a HTTP status code 405: method not allowed if the client has not been registered yet.

Just to be sure, is this POST the first one ?

**Comment by Llocer** [comment]
closed due to author inactivity
